### Criar usuário
POST http://localhost:3003/signup
Content-Type: application/json

{
	"name": "João",
	"email": "joao@email.com",
	"password": "123456"
}

### Login
POST http://localhost:3003/login
Content-Type: application/json

{
	"email": "joao@email.com",
	"password": "123456"
}

### Pegar próprio perfil
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4ODNmNzIxLTZjNDAtNDQ0OC1hNDM0LWI1MDg2ZmZmODE1MiIsImlhdCI6MTYxMTg2NjI1NiwiZXhwIjoxNjExODY2ODU2fQ.Cwg82WFHvXogBDxQYO-rmP9hSEIswanHa3pREZ2OERI

### Pegar próprio perfil
GET http://localhost:3003/user/be54c071-8f48-4d08-8419-8ad16606d3c6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4ODNmNzIxLTZjNDAtNDQ0OC1hNDM0LWI1MDg2ZmZmODE1MiIsImlhdCI6MTYxMTg2NjI1NiwiZXhwIjoxNjExODY2ODU2fQ.Cwg82WFHvXogBDxQYO-rmP9hSEIswanHa3pREZ2OERI