### Criar usuário
POST http://localhost:3003/signup
Content-Type: application/json

{
	"name": "João",
	"email": "joao@email.com",
	"password": "123456"
}

### Login
POST http://localhost:3003/login
Content-Type: application/json

{
	"email": "nohah@email.com",
	"password": "123456"
}

### Pegar próprio perfil
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4ODNmNzIxLTZjNDAtNDQ0OC1hNDM0LWI1MDg2ZmZmODE1MiIsImlhdCI6MTYxMTk3MzAzMiwiZXhwIjoxNjExOTc0ODMyfQ.RqA-DCO5rlBPt-l3KqClL4mDapRJ4bP3GPaUI-rnYrY

### Pegar perfil de outro usuário
GET http://localhost:3003/user/be54c071-8f48-4d08-8419-8ad16606d3c6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlNTRjMDcxLThmNDgtNGQwOC04NDE5LThhZDE2NjA2ZDNjNiIsImlhdCI6MTYxMTk2MzkwMSwiZXhwIjoxNjExOTY1NzAxfQ.TSyeBHDqwSYSCxl4hFhOtlPmr0ZPEIscm0P6BjE9RNg

### Criar receita
POST http://localhost:3003/recipe
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiNDcwYTE2LTVkZDYtNGJhZS05NmJmLWE4ZTllMjUyYzU4OSIsImlhdCI6MTYxMjA5MzMxNiwiZXhwIjoxNjEyMDk1MTE2fQ.o_7E0o3OtSQz2CEP3yaPNx16jNynZGIbUfst_HeCoYc
Content-Type: application/json

{
	"title": "Doce de leite",
	"description": "doce + leite"
}

### Pegar receita
GET http://localhost:3003/recipe/6fd46733-35a4-4418-9ea2-29bee8915246
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlNTRjMDcxLThmNDgtNGQwOC04NDE5LThhZDE2NjA2ZDNjNiIsImlhdCI6MTYxMTk2MzkwMSwiZXhwIjoxNjExOTY1NzAxfQ.TSyeBHDqwSYSCxl4hFhOtlPmr0ZPEIscm0P6BjE9RNg

### Seguir usuário
POST http://localhost:3003/user/follow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4ODNmNzIxLTZjNDAtNDQ0OC1hNDM0LWI1MDg2ZmZmODE1MiIsImlhdCI6MTYxMTk3NDAxMCwiZXhwIjoxNjExOTc1ODEwfQ.PGvBh4SffD3suQYSScZWP7v5ib6fRnDlNtSHGAfc-TM
Content-Type: application/json

{
	"userToFollowId": "be54c071-8f48-4d08-8419-8ad16606d3c6"
}

### Deixar de seguir usuário
POST http://localhost:3003/user/unfollow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4ODNmNzIxLTZjNDAtNDQ0OC1hNDM0LWI1MDg2ZmZmODE1MiIsImlhdCI6MTYxMTk3MzAzMiwiZXhwIjoxNjExOTc0ODMyfQ.RqA-DCO5rlBPt-l3KqClL4mDapRJ4bP3GPaUI-rnYrY
Content-Type: application/json

{
	"userToUnfollowId": "be54c071-8f48-4d08-8419-8ad16606d3c6"
}

### Pegar feed de receitas
GET  http://localhost:3003/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlNTRjMDcxLThmNDgtNGQwOC04NDE5LThhZDE2NjA2ZDNjNiIsImlhdCI6MTYxMjA5NDM5NywiZXhwIjoxNjEyMDk2MTk3fQ.6H-7vtsxg-DAcgkw74G3urFk2li5kJfStaywY1S24-Q